### ISSUE TITLE
Write to DICOM for PET modality

### ISSUE THREAD

**Issue by ClaireDelplancke** [scikit-rt/scikit-rt#2]
I'd like to write to DICOM a PET image. I've tried:
```
header_extras = {
    "Media Storage SOP Class UID" : "UI: Positron Emission Tomography Image Storage",
    "SOP Class UID" : "UI: Positron Emission Tomography Image Storage",
    "Modality" : "PT"
    }
im.write("my_image_dicom",  root_uid=root_uid, header_extras=header_extras)
```
However, only the "Modality" field gets changed in the resulting DICOM files, the fields "Media Storage SOP Class UID" and "SOP Class UID" are not changed.

**Comment by kh296** [comment]
Modality and related metadata should be set via the `modality` argument when calling `im.write()`.  Unfortunately, only a selection of modalities are supported, basically because we haven't had data for testing them.  I've added `PT` to the list, so you should now be able to do:

```
im.write('my_image_dicom', root_uid=root_uid, modality='PT')
```
Could you give this a try?

The `header_extras` dictionary is for data elements, and doesn't work for file metadata.

**Comment by ClaireDelplancke** [comment]
It works, thanks!
