### ISSUE TITLE
CT voxel dimensions when importing via Patient & Study class vs Image Class

### ISSUE THREAD

**Issue by DrRajJena** [scikit-rt/scikit-rt#8]
Hello. 
I have come across an issue where the reported voxel dimensions from a DICOM CT image dataset seem to vary depending on the import technique. 

I have been using this code snippet  from [https://github.com/scikit-rt/scikit-rt/blob/master/examples/notebooks/plotting_demo.ipynb](url)  as a template to import DICOM CT, structure set and Dose cube in the same reference frame for a script I am developing.

_Obtain sorted list of paths to patient folders._
paths = sorted(list(datadir.glob("*")))
_Define index for path to patient folder of interest._
idx = 0
_Read patient data._
patient = Patient(paths[idx], unsorted_dicom=True)
_Identify study containing ct_image, ct_structure_set, ct_dose. If no study contains all of these data types, an exception will be raised._
for study in patient.studies + [None]:
    if all(["ct" in getattr(study, f"{dtype}_types", [])
            for dtype in ["image", "structure_set", "dose"]]):
        break
if study is None:
    raise RuntimeError("No study found with required data types")
_Obtain reference to earliest CT image._ 
im1 = study.ct_images[0]
print(im1.affine)
print(im1.voxel_size)

This returns **None** for affine and **[1, 1, 1]** for voxel_size. This was not expected. However, import using the skrt Image object works correctly.

im2 = Image(directdir)
print(im2.affine)
print(im2.voxel_size)

Returns the expected values:
[[   1.9531        0.            0.         -263.18359375]
 [   0.            1.9531        0.         -265.13668823]
 [   0.            0.            3.          -96.5       ]
 [   0.            0.            0.            1.        ]]
[1.9531, 1.9531, 3.0]

Have I misunderstood how the Patient and Study classes should work when importing DICOM data?

I did note that im1.dicom_dataset attribute is set to **None**, whilst im2.dicom_dataset attribute is set to **<class 'pydicom.dataset.FileDataset'>**

Thank you

**Comment by kh296** [comment]
You should hopefully obtain the expected behaviour if you use the getter methods:

```
im1 = study.ct_images[0]
print(im1.get_affine())
print(im1.get_voxel_size())
```
Let me know if this doesn't work for you.

I've updated the code documentation for [Image](https://scikit-rt.github.io/scikit-rt/skrt.image.html#skrt.image.Image), [Dose](https://scikit-rt.github.io/scikit-rt/skrt.dose.html#skrt.dose.Dose), [ROI](https://scikit-rt.github.io/scikit-rt/skrt.structures.html#skrt.structures.ROI), [StructureSet](https://scikit-rt.github.io/scikit-rt/skrt.structures.html#skrt.structures.StructureSet), [Plan](https://scikit-rt.github.io/scikit-rt/skrt.dose.html#skrt.dose.Plan), to include the recommendation that object attributes be accessed using their getter methods, rather than directly.

I've added to the high-level documentation a note on [data loading](https://scikit-rt.github.io/scikit-rt/usage.html#data-loading), outlining the strategy used with the `Patient` and `Study` class of loading data when needed.

**Comment by DrRajJena** [comment]
This shows the expected behaviour.  Issue closed. Thanks.
